name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linux64_build:
    name: Linux x86_64 Build
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Build"
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse
          git clone --recursive https://github.com/wez/wezterm
          cd wezterm
          bash ../patch.sh
          env CI=yes PATH=$PATH ./get-deps
          cargo build --all --release
          bash ci/deploy.sh
          bash ci/source-archive.sh
          bash ci/appimage.sh
      - name: Set Name Variables
        run: |
          echo "version=$(git describe)" >> $GITHUB_ENV
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "ubuntu-${{ env.folder_name }}"
          path: |
            wezterm/wezterm-*.deb
            wezterm/wezterm-*.xz
            wezterm/*src.tar.gz
            wezterm/*.AppImage
            wezterm/*.zsync

  windows64_build:
    name: Windows x86_64 Build
    runs-on: windows-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Prebuild"
        shell: bash
        run: |
          git clone --recursive https://github.com/wez/wezterm
          cd wezterm
          bash ../patch.sh
      - name: "Build"
        shell: cmd
        run: |
          cd wezterm
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build --all --release
      - name: "Package"
        shell: bash
        run: |
          cd wezterm
          bash ci/deploy.sh
      - name: Set Name Variables
        run: |
          echo "version=$(git describe)" >> $GITHUB_ENV
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "windows-${{ env.folder_name }}"
          path: |
            wezterm/WezTerm-*.zip
            wezterm/WezTerm-*.exe

  macos_build:
    name: macOS Build
    runs-on: "macos-11"
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Build"
        shell: bash
        run: |
          git clone --recursive https://github.com/wez/wezterm
          cd wezterm
          bash ../patch.sh
          env CI=yes PATH=$PATH ./get-deps
          cargo build --target x86_64-apple-darwin --all --release
          cargo build --target aarch64-apple-darwin --all --release
          bash ci/deploy.sh
      - name: Set Name Variables
        run: |
          echo "version=$(git describe)" >> $GITHUB_ENV
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "macos-${{ env.folder_name }}"
          path: "wezterm/WezTerm-*.zip"
